runtime: python
instance_class: F4
env: flex
entrypoint: gunicorn -b :$PORT app:app

readiness_check:
  initial_delay_sec: 3600
  app_start_timeout_sec: 1800

handlers:
- url: /public
  static_dir: public

runtime_config:
  python_version: 3


