runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

readiness_check:
  timeout_sec: 1000
  app_start_timeout_sec: 1000

handlers:
- url: /public
  static_dir: public

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 1