runtime: python
instance_class: F4
env: flex
entrypoint: gunicorn -b :$PORT app:app --timeout 400

liveness_check:
  initial_delay_sec: 400

readiness_check:
  app_start_timeout_sec: 400

handlers:
- url: /public
  static_dir: public

runtime_config:
  python_version: 3


