runtime: python
instance_class: F4
env: flex
entrypoint: gunicorn -t 60 -b :$PORT app:app

liveness_check:
  initial_delay_sec: 500

readiness_check:
  app_start_timeout_sec: 500

handlers:
- url: /public
  static_dir: public

runtime_config:
  python_version: 3


