runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /public
  static_dir: public

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 0.5