runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

readiness_check:
  timeout_sec: 1000
  app_start_timeout_sec: 1000

handlers:
- url: /public
  static_dir: public

runtime_config:
  python_version: 3

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50